<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ssm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Fin\Fin\Fin.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Gx\Gx\Gx.csproj" />
  </ItemGroup>

</Project>
