namespace mkdd.schema.bol;

public static class ObjectIdUtil {
  /// <summary>
  ///   Shamelessly copied from => 
  ///   https => //github.com/magcius/noclip.website/blob/main/src/j3d/mkdd_scenes.ts
  /// </summary>
  public static string[][]? GetFileNames(ushort objectId) {
    // Each object has code which decides what files to load
    // For now just simply hardcode which object should load what files
    // Objects =>  https => //avsys.xyz/wiki/Mario_Kart_Double_Dash/Object
    return objectId switch {
        0x0001 => null,
        0x0003 => [["njump.bmd"]],
        0x0007 => null,
        0x0009 => null,
        0x000A => null,
        0x000E => null,
        0x0010 => null,
        0x0011 => [["sun.bmd", "sun.btk"]],
        0x0013 => null,
        0x0014 => null,
        0x0CE5 => [["babykanran.bmd"]],
        0x0CE6 => [["babyjet_body.bmd"]],
        0x0CE8 => [["yoshihelib.bmd", "yoshihelib.btk"]],
        0x0D49 => [
          ["sea1_spc.bmd", "sea1_spc.btk"],
          ["sea2_tex.bmd", "sea2_tex.btk"],
          ["sea3_dark.bmd"],
          ["sea4_nami.bmd"],
          ["sea5_sand.bmd"],
        ],
        0x0D4A => [["poihana1.bmd", "poihana1_wait.bck"]],
        0x0D4B => null,
        0x0D4D => [["peachtree1.bmd", "peachtree1_wait.bck"]],
        0x0D4E => [["peachfountain.bmd", "peachfountain.btk"]],
        0x0D4F => [["marel_a.bmd", "marel_a_clap1.bck"]],
        0x0D50 => [["marel_b.bmd", "marel_a_clap1.bck"]],
        0x0D51 => [["marel_c.bmd", "marel_a_clap1.bck"]],
        0x0D52 => [["monl_a.bmd", "monl_a_clap1.bck"]],
        0x0D53 => [["monl_b.bmd", "monl_a_clap1.bck"]],
        0x0D54 => [["monl_c.bmd", "monl_a_clap1.bck"]],
        0x0D55 => [["uklele_monte.bmd", "uklele_monte.bck"]],
        0x0D56 => [["monf_a.bmd", "monf_a_dance.bck"]],
        0x0D57 => [["monf_b.bmd", "monf_a_dance.bck"]],
        0x0D58 => [["monl_d.bmd", "monl_a_clap1.bck"]],
        0x0D59 => [["monl_e.bmd", "monl_a_clap1.bck"]],
        0x0D5A => [["marew_a.bmd", "marew_a_dance.bck"]],
        0x0D5B => [["marew_b.bmd", "marew_a_dance.bck"]],
        0x0D5C => [["marew_c.bmd", "marew_a_dance.bck"]],
        0x0D5D => [["marem_a.bmd", "marem_a.bck"]],
        0x0D66 => null,
        0x0D7A => null,
        0x0D7B => [["demo_k_body.bmd"]],
        0x0D7C => [["kinojii.bmd", "kinojii_drive.bca", "kinojii_wink.btp"]],
        0x0D7D => [["dpeachfountain.bmd", "dpeachfountain.btk"]],
        0x0D7E => null,
        0x0D7F => [["peachtree2.bmd", "peachtree2_wait.bck"]],
        0x0DAE => null,
        0x0DAF => [["pool.bmd", "pool.btk"]],
        0x0DB1 => [["fan1.bmd"]],
        0x0E0E => null,
        0x0E0F => [["testwall1.bmd"]],
        0x0E75 => [["mariotree1.bmd", "mariotree1_wait.bck"]],
        0x0E77 => [["marioflower1.bmd", "marioflower1.bck"]],
        0x0E78 => null,
        0x0E7E => [["skyship1.bmd"]],
        0x0E7F => [["kuribo1.bmd"]],
        0x0E80 => [["pakkun.bmd", "pakkun_wait.bca"]],
        0x0E82 => [["mash_balloon.bmd"]],
        0x0ED9 => [["yoshiheli.bmd", "yoshiheli.btk"]],
        0x0FA1 => [["car_public1.bmd", "car_public1.btk"]],
        0x0FA2 => [["car_bus1.bmd", "car_bus1.btk"]],
        0x0FA3 => [["car_truck1.bmd", "car_truck1.btk"]],
        0x0FA4 => [["signal1.bmd", "signal1.brk"]],
        0x0FA5 => [["car_bomb1.bmd", "car_bomb1.btk"]],
        0x0FA6 => [["car_kinoko1.bmd", "car_kinoko1.btk"]],
        0x0FA8 => [["car_item1.bmd", "car_item1.btk"]],
        0x0FA9 => [["car_hana1.bmd"]],
        0x1069 => [["firebar1.bmd"]],
        0x106B => null,
        0x106D => [["wl_screen1.bmd"]],
        0x106E => [["wl_wall1.bmd", "wl_wall1.bca"]],
        0x106F => [["wlarrow1.bmd", "wlarrow1.bck", "wlarrow1.btk"]],
        0x1070 => [["wl_dokan1.bmd"]],
        0x1071 => null,
        0x1072 => [["wa_search1.bmd", "wa_search1.bck"]],
        0x1098 => [["donkytree1.bmd", "donkytree1_wait.bck"]],
        0x1099 => [["donkywood.bmd"]],
        0x1195 => null,
        0x1196 => null,
        0x119A => null,
        0x119C => null,
        0x119E => [["geyser1.bmd", "geyser1.btk", "geyser12.bca"]],
        0x11A1 => [["nossie.bmd", "nossie.bca"]],
        0x11A4 => [["dinotree1.bmd", "dinotree1_wait.bck"]],
        0x11A5 => [["swimnossie.bmd", "swimnossie.bca"]],
        0x11A6 => [["ptera.bmd", "pteraflya.bck"]],
        0x125D => [["dossun1.bmd"]],
        0x125E => [["bubble1.bmd", "bubble1.btk"]],
        0x125F => [["kpfire1.bmd", "kpfire1.bck"]],
        0x1261 => [["kpgear1.bmd", "kpgear1.bck"]],
        0x1262 => null,
        0x1327 => null,
        0x1389 => [["sanbo1.bmd"]],
        0x138B => [["tornado.bmd", "tornado.bca", "tornado.btk"]],
        0x138C => [["deballoon1.bmd"]],
        0x138F => [["antlion.bmd", "antlion_eat.bck"]],
        0x1390 => null,
        0x1391 => null,
        0x1392 => [["deserttree1.bmd"]],
        0x13ED => [["snowrock1.bmd"]],
        0x13EE => [["heyho1.bmd", "heyho1.bca"]],
        0x13F0 => [["snowman1.bmd"]],
        0x13F3 => [["lights1.bmd"]],
        0x13F4 => null,
        0x26B2 => null,
        _ => throw new ArgumentOutOfRangeException(
            nameof(objectId),
            objectId,
            null)
    };
  }
}