<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>sysdolphin</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Fin\Fin\Fin.csproj" />
    <ProjectReference Include="..\..\Gx\Gx\Gx.csproj" />
  </ItemGroup>

</Project>
