<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Fin\Fin.Picross\Fin.Picross.csproj" />
    <ProjectReference Include="..\..\..\Fin\Fin\Fin.csproj" />
  </ItemGroup>

</Project>
