<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>pm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="schema" Version="0.6.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Fin\Fin.Compression\Fin.Compression.csproj" />
    <ProjectReference Include="..\..\..\Fin\Fin\Fin.csproj" />
    <ProjectReference Include="..\..\..\Libraries\F3dzex2\F3dzex2\F3dzex2.csproj" />
  </ItemGroup>

</Project>
