<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sledge.Formats.Map" Version="1.2.9" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\..\Fin\Fin\Fin.csproj" />
	<ProjectReference Include="..\..\..\Fin\Fin.Ui\Fin.Ui.csproj" />
  </ItemGroup>

</Project>
